### ISSUE TITLE
Prod Orgs show under "Dev Orgs" grouping

### ISSUE THREAD

**Issue by petethurston** [RevCult/sfdx-frontend#2]
Not sure if it's possible to segregate or allow user to declare when adding?

![image](https://user-images.githubusercontent.com/2215110/36456926-4f08f11e-165c-11e8-8beb-2dff1999b625.png)

**Comment by keaganhilliard** [comment]
Hmmm... So, we would then have to store our own information about each entry. Or possibly just go off of instance url and lump dev orgs and prod orgs together.
